### PR TITLE
define the environment variable COURSES_DIRECTORY_ON_HOST in .env

### PR DESCRIPTION
**Pull request by heiderich**
and use it instead of the hard-coded string "../ww-docker-data/courses" in
`docker-compose.yml`.

Note that the file `.env` is read by `docker-compose` and that values defined there can be overwritten by changing the environment variables of `docker-compose`. See

https://docs.docker.com/compose/environment-variables/

for more details.

If there is agreement on using that approach, we can later on define more environment variables in the `.env` file and parameterize the `docker-compose.yml` file in that way.

### CODE REVIEW

**Comment by taniwallach** [comment]
@heiderich - Have you tested this. If so, I will merge it.

**Comment by heiderich** [comment]
Modulo the missing files

```
/opt/webwork/webwork2/bin/restore-OPL-tables
/opt/webwork/webwork2/bin/dump-OPL-tables
/opt/webwork/webwork2/bin/load-OPL-global-statistics
```

it seems to work.

However you can run into problems if you start up the docker containers with one value for  `COURSES_DIRECTORY_ON_HOST`, create a course and then change the value of `COURSES_DIRECTORY_ON_HOST`. You end up in a state where the SQL database holds tables for the course created, while it does not exist in the (new) course directory. This was however also a problem in the previous setup when the bind mount was changed.

I did my tests in linux with the following versions: 

```
$ docker-compose --version
docker-compose version 1.22.0, build f46880fe
$ docker --version
Docker version 19.03.1, build 74b1e89
```

**Comment by heiderich** [comment]
In f4d3573 I introduce another environment variable to control the HTTP port on the host system. I think this is helpful for people who want to start containers on different ports.

Unfortunately I do not know yet how to handle the HTTPS port. It seems that it is not always opened in the container. So we would need a conditional here. It seems that docker-compose (currently) cannot handle this. Maybe we can later on provide different versions of the `docker-compose.yml` and `.env` file for different purposes (one with SSL enabled and one without).

**Comment by taniwallach** [comment]
Looks good to me.

I don't think https/SSL should be on by default. For local development on a personal machine it is not necessary, and for real use a valid SSL key+certificate pair is needed.

**Pull request merged**
